/* Copyright (C) 2022 Simo Sorce <simo@redhat.com>
   SPDX-License-Identifier: Apache-2.0 */

/* DO NOT EDIT, autogenerated from encoder.h.pre */
/* Modify encoder.h.pre then run make generate-code */

#ifndef _ENCODER_GEN_H
#include <openssl/asn1t.h>
#include <openssl/pem.h>

typedef struct {
    ASN1_INTEGER *n;
    ASN1_INTEGER *e;
} P11PROV_RSA_PUBKEY;

extern P11PROV_RSA_PUBKEY *P11PROV_RSA_PUBKEY_new(void);
extern void P11PROV_RSA_PUBKEY_free(P11PROV_RSA_PUBKEY *a);
extern P11PROV_RSA_PUBKEY *d2i_P11PROV_RSA_PUBKEY(P11PROV_RSA_PUBKEY **a,
                                                  const unsigned char **in,
                                                  long len);
extern int i2d_P11PROV_RSA_PUBKEY(const P11PROV_RSA_PUBKEY *a,
                                  unsigned char **out);
extern const ASN1_ITEM *P11PROV_RSA_PUBKEY_it(void);
extern int PEM_write_bio_P11PROV_RSA_PUBKEY(BIO *out,
                                            const P11PROV_RSA_PUBKEY *x);

typedef struct {
    ASN1_OBJECT *type;
    ASN1_INTEGER *key_type;
    ASN1_UTF8STRING *uri;
} P11PROV_KEYPAIR_REF;

extern P11PROV_KEYPAIR_REF *P11PROV_KEYPAIR_REF_new(void);
extern void P11PROV_KEYPAIR_REF_free(P11PROV_KEYPAIR_REF *a);
extern P11PROV_KEYPAIR_REF *d2i_P11PROV_KEYPAIR_REF(P11PROV_KEYPAIR_REF **a,
                                                    const unsigned char **in,
                                                    long len);
extern int i2d_P11PROV_KEYPAIR_REF(const P11PROV_KEYPAIR_REF *a,
                                   unsigned char **out);
extern const ASN1_ITEM *P11PROV_KEYPAIR_REF_it(void);
extern int PEM_write_bio_P11PROV_KEYPAIR_REF(BIO *out,
                                             const P11PROV_KEYPAIR_REF *x);
extern P11PROV_KEYPAIR_REF *
PEM_read_bio_P11PROV_KEYPAIR_REF(BIO *out, P11PROV_KEYPAIR_REF **x,
                                 pem_password_cb *cb, void *u);

#endif
